image:
  name: ${DOCKER_REPO}:master

variables:
  DOCKER_REPO: registry.gitlab.int.windscribe.com:5005/ws/client/extension-mv3
  #TEST_USER_NAME: "sample"         # Set in Gitlab variables
  #TEST_USER_PASSWORD: "PaSsWoRd"  # Set in Gitlab variables


stages:
  - prepare_environment
  - install_packages
  - test
  - build

build:image:
  image: docker
  stage: prepare_environment
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - Dockerfile
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${DOCKER_REPO}:master .
    - docker push ${DOCKER_REPO}:master

install:
  stage: install_packages
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/

eslint:
  stage: test
  needs:
    - job: install
  script:
    - yarn run lint

test:
  stage: test
  needs:
    - job: install
  dependencies:
    - install
  script:
    - printf "\nNODE_ENV=CI" >> ".env"
    - printf "\nAPI_URL=staging.windscribe.com" >> ".env"
    - printf "\nTEST_USER_NAME=$TEST_USER_NAME" >> ".env"
    - printf "\nTEST_USER_PASSWORD=$TEST_USER_PASSWORD" >> ".env"
    - yarn run build
    - Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 & # Start virtual display
    - yarn run test

build:extension:
  stage: build
  needs: ["install", "eslint", "test"]
  dependencies:
    - install
  before_script:
    - echo "checking node version"
    - node -v
  script:
  - printf "\nNODE_ENV=production" >> ".env"
  - printf "\nAPI_URL=windscribe.com" >> ".env"
  - printf "\nBACKUP_API_URL=totallyacdn.com" >> ".env"
  - yarn run build 
  artifacts:
    paths:
      - build/
    expire_in: 7 days
