image:
  name: ${DOCKER_REPO}:master
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  CI: "true"
  DOCKER_REPO: registry.gitlab.int.windscribe.com:5005/ws/client/extension-mv3

stages:
  - prepare-environment
  - lint
  - build
  - test

build:image:
  image: docker
  stage: prepare-environment
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "master"
  #     changes:
  #       - Dockerfile
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f e2e.Dockerfile -t ${DOCKER_REPO}:${CI_COMMIT_REF_SLUG} .
    - docker push ${DOCKER_REPO}:${CI_COMMIT_REF_SLUG}

eslint:
  stage: lint
  needs:
    - job: build:container
  script:
  - yarn install --frozen-lockfile
  - yarn run lint
  artifacts:
    paths:
      - node_modules/
    expire_in: 7 days

build:extension:
  stage: build
  needs:
    - job: eslint
  before_script:
    - echo "checking node version"
    - node -v
  script:
  - printf "\nNODE_ENV=CI" >> ".env"
  - yarn run build 
  artifacts:
    paths:
      - build/
    expire_in: 7 days

test:
  stage: test
  needs:
    - job: eslint
    - job: build:extension
  script:
    - Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 & # Start virtual display
    - yarn run test