image: digitalcatharsis/gitlab-ci-puppeteer-headful:latest

variables:
  CI: "true"

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - echo "checking node version"
    - node -v
  script:
  - yarn install --frozen-lockfile
  - yarn run build
  cache:
    paths:
      - node_modules/

test:
  stage: test
  before_script:
    - echo "checking node version"
    - node -v
  script:
    - Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 & # Start virtual display
    - yarn run test